package ExceptionHandling;

import java.io.IOException;

public class ExceptionHandlingDemo {

	public static void main(String[] args) {
		
		try {
			System.out.println("Vor");
			throwIOExeption();
			throwIllegalArgumentException();
			System.out.println("Nach  der IOEx");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			System.out.println("Vor dem catch der IOEx");
			e.printStackTrace();
			System.out.println("Nach dem catch der IOEx");
		} catch (IllegalArgumentException e){
			System.out.println("Vor dem catch der IllArg");
			e.printStackTrace();
			System.out.println("Nach dem catch der IllArg");
		}
		
		
		
//		throwTrhowable();
//		throwAssertionError();
		
	}

	private static void throwIOExeption() throws IOException {
		throw new IOException("My message here");	
	}
	
	private static void throwIllegalArgumentException() throws IllegalArgumentException{
		throw new IllegalArgumentException("Simona is here");
	}
	
}
